name: Deployment Pipeline

on:
    push:
        branches: ['main']

    pull_request:
        branches: ['main']
        types: [opened, synchronize]
jobs:
    avoid_reduncy:
        runs-on: ubuntu-20.04
        steps:
            - name: Cancel Previus Redudant Builds
            - uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}
